### ISSUE TITLE
Is it possible to hide the toolbar only by a set height?

### ISSUE THREAD

**Issue by dylan-kwon** [onebone/compose-collapsing-toolbar#70] opened 2023-01-04 07:40 UTC
Is it possible to hide the toolbar only by a set height?

For example I want to hide a 100dp tall toolbar by only 50dp using `ScrollStrategy.EnterAlways`.

**Comment by onebone** [comment] 2023-01-04 08:44
Looks like it is a duplicate of #68. Let me know if it is a mistake!

**Closed** 2023-01-04 08:44 UTC
