### ISSUE TITLE
Expand when needed

### ISSUE THREAD

**Issue by alashow** [onebone/compose-collapsing-toolbar#5] opened 2021-07-03 02:01 UTC
Hello. This works great for collapsing toolbars, but is there a way to expand/collapse the toolbar when needed?

My use case is that I have a search input on the toolbar and I want to expand the toolbar when keyboard is visible (via [`LocalWindowInsets.current.ime.isVisible`](https://google.github.io/accompanist/insets/))

**Comment by onebone** [comment] 2021-09-04 15:06
This feature has just released as experimental in 2.2.0 with `CollapsingToolbarState.expand()` :+1:

**Closed by onebone** 2021-09-04 15:06 UTC
Labels: enhancement

**Comment by onebone** [comment] 2021-09-25 07:14
@Shusshu May I ask you to create a new issue with some extra information so that I could reproduce it?

**Comment by alashow** [comment] 2021-09-25 07:45
https://issuetracker.google.com/issues/197553056 could be related

**Comment by onebone** [comment] 2021-09-25 08:10
> https://issuetracker.google.com/issues/197553056 could be related

Thank you for sharing 😃 Since I have experienced some trouble regarding that issue when I was testing fling behaviors, it is happy to hear that it has fixed. But how can it be related to the manual collapsing/expansion using animators?

**Comment by alashow** [comment] 2021-09-25 11:16
I accidentally thought this thread was about flings again, nvm 😬
